# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6525aa7ac480041460a3f53dabfced470f3728d2edeb75f05a4a16cc6e40246c50ecb7d3bdbce474ded1dd551c929475a4de1fd2d279c19a82a5a0e66431078

test:
  secret_key_base: b41fd2cff892465ef2ddb94eda9016d6628ab14ac3b0a34418d85d5c73adfcbd86de4e89c8a7133790bd5ee40d086ae0f27751d75c6be4a7527cd016493525be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
